### ISSUE TITLE
Clase cociente

### ISSUE THREAD

**Issue by aseguragonzalez** [G5-MP0487-Edix/AE-2.Activities#5]
# Clase cociente

## Requisitos
Esta clase implementará todos los métodos que están relacionados con la división de la calculadora. Esta clase tendrá los siguientes métodos:
1. División de dos números reales, tendrá 2 parámetros de entrada y uno de salida que será la solución.
1. División de dos números enteros, tendrá 2 parámetros de entrada y uno de salida que será la solución.
1. Inverso de un número real, tendrá un parámetro de entrada y uno de salida que será la solución.
1. Raíz de un número, tendrá un parámetro de entra y uno de salida que será la solución. Valoración: 6 puntos sobre 10

## Tareas
- [x] #8
- [ ] Agregar pruebas del funcionamiento de la clase en el método main.
- [ ] Revisión de la documentación de la clase.

**Comment by tiznajo** [comment]
Implementado el requerimiento 1 de la actividad 2 en lo referente a la clase cociente. Descripción en [https://github.com/G5-MP0487-Edix/AE-2.Activities/issues/8](url)
